# Generated by Django 5.0.3 on 2024-03-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('weapon', models.CharField(max_length=100)),
                ('ability', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
