# Generated by Django 5.0.3 on 2024-03-24 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='files/character_image'),
            preserve_default=False,
        ),
    ]
