# Generated by Django 5.0.3 on 2024-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_category_alter_character_image_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='anime',
            field=models.ManyToManyField(blank=True, to='App.anime'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.ImageField(null=True, upload_to='App/files/character_image'),
        ),
    ]
