# Generated by Django 5.0.3 on 2024-03-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_genre_studio_rename_desctipion_anime_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='genre',
        ),
        migrations.AddField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(blank=True, to='App.genre'),
        ),
    ]
